curl -H 'Content-Type: application/json' -d '
{
  "sessionId":null,
  "payload":{
    "symId":null,
    "dk1":null,
    "hashField":null,
    "semanticDescription":[
      {
        "internalId":null,
        "pluginId":null,
        "cloudMonitoringHost":null,
        "singleTokenAccessPolicy":null,
        "singleTokenFilteringPolicy":null,
        "resource":{
          "@c":".Sensor",
          "observesProperty":null,
          "id":null,
          "name":null,
          "description":null,
          "interworkingServiceURL":null,
          "locatedAt":null,
          "services":[
            {
              "@c":".Service",
              "id":null,
              "name":null,
              "description":null,
              "interworkingServiceURL":null,
              "resultType":null,
              "parameters":[
                {
                  "name":"param1",
                  "mandatory":false,
                  "restrictions":null,
                  "datatype":null
                }
              ]
            }
          ]
        },
        "params":null
      },
      {
        "internalId":null,
        "pluginId":null,
        "cloudMonitoringHost":null,
        "singleTokenAccessPolicy":null,
        "singleTokenFilteringPolicy":null,
        "resource":{
          "@c":".Actuator",
          "id":null,
          "name":null,
          "description":null,
          "interworkingServiceURL":null,
          "locatedAt":null,
          "services":null,
          "capabilites":null
        },
        "params":null
      }
    ],
    "connectedTo":null,
    "available":false,
    "agentType":"SDEV"
  }
}
' -X POST -D - http://localhost:8080/innkeeper/registry
